import * as Tone from "tone";

import { Organ } from "./Organ";
import { Rhodes } from "./Rhodes";

import type { Instrument } from "./Instrument";

export type InstrumentType =
  | "ORGAN"
  | "RHODES";

export class AudioEngine {

  private instrument: Instrument;

  private instrumentType:
    InstrumentType =
    "ORGAN";

  private volume =
    0.3;

  /*
  |--------------------------------------------------------------------------
  | RECORDING AUDIO DESTINATION
  |--------------------------------------------------------------------------
  |
  | Tone audio continues going to the speakers normally.
  |
  | We additionally tap the Tone master destination and send the same
  | audio into a MediaStreamAudioDestinationNode for MediaRecorder.
  |
  |--------------------------------------------------------------------------
  */

  private recordingDestination:
    MediaStreamAudioDestinationNode | null =
    null;


  /*
  |--------------------------------------------------------------------------
  | CONSTRUCTOR
  |--------------------------------------------------------------------------
  */

  constructor() {

    this.instrument =
      new Organ();

  }


  /*
  |--------------------------------------------------------------------------
  | START
  |--------------------------------------------------------------------------
  */

  async start(): Promise<void> {

    await Tone.start();

    if (
      Tone.getContext().state !==
      "running"
    ) {

      await Tone.getContext()
        .resume();

    }

  }


  /*
  |--------------------------------------------------------------------------
  | PLAY
  |--------------------------------------------------------------------------
  */

  play(
    notes: string[]
  ): void {

    if (
      notes.length === 0
    ) {

      return;

    }

    this.instrument.play(
      notes
    );

  }


  /*
  |--------------------------------------------------------------------------
  | STOP
  |--------------------------------------------------------------------------
  */

  stop(): void {

    this.instrument.stop();

  }


  /*
  |--------------------------------------------------------------------------
  | VOLUME
  |--------------------------------------------------------------------------
  */

  setVolume(
    value: number
  ): void {

    this.volume =
      Math.max(
        0,
        Math.min(
          1,
          value
        )
      );

    this.instrument.setVolume(
      this.volume
    );

  }


  /*
  |--------------------------------------------------------------------------
  | FILTER
  |--------------------------------------------------------------------------
  */

  setFilter(
    frequency: number
  ): void {

    this.instrument.setFilter(
      frequency
    );

  }


  /*
  |--------------------------------------------------------------------------
  | INSTRUMENT
  |--------------------------------------------------------------------------
  */

  setInstrument(
    type: InstrumentType
  ): void {

    if (
      type ===
      this.instrumentType
    ) {

      return;

    }


    /*
    |--------------------------------------------------------------------------
    | STOP OLD INSTRUMENT
    |--------------------------------------------------------------------------
    */

    this.instrument.stop();


    /*
    |--------------------------------------------------------------------------
    | DISPOSE OLD TONE NODES
    |--------------------------------------------------------------------------
    */

    this.instrument.dispose();


    /*
    |--------------------------------------------------------------------------
    | CREATE NEW INSTRUMENT
    |--------------------------------------------------------------------------
    */

    if (
      type ===
      "ORGAN"
    ) {

      this.instrument =
        new Organ();

    } else {

      this.instrument =
        new Rhodes();

    }


    /*
    |--------------------------------------------------------------------------
    | RESTORE VOLUME
    |--------------------------------------------------------------------------
    */

    this.instrument.setVolume(
      this.volume
    );


    this.instrumentType =
      type;

  }


  /*
  |--------------------------------------------------------------------------
  | GET INSTRUMENT
  |--------------------------------------------------------------------------
  */

  getInstrument():
    InstrumentType {

    return this.instrumentType;

  }


  /*
  |--------------------------------------------------------------------------
  | RECORDING STREAM
  |--------------------------------------------------------------------------
  |
  | Returns the exact audio generated by Tone.js.
  |
  | The first call creates the destination.
  | Later calls reuse it.
  |
  |--------------------------------------------------------------------------
  */

  getRecordingStream():
    MediaStream {

    if (
      !this.recordingDestination
    ) {

      this.recordingDestination =
        Tone.getContext()
          .createMediaStreamDestination();


      /*
      |--------------------------------------------------------------------------
      | TONE MASTER → RECORDING
      |--------------------------------------------------------------------------
      */

      Tone.getDestination()
        .connect(
          this.recordingDestination
        );

    }


    return this.recordingDestination
      .stream;

  }


  /*
  |--------------------------------------------------------------------------
  | DISPOSE
  |--------------------------------------------------------------------------
  */

  dispose(): void {

    this.instrument.dispose();


    if (
      this.recordingDestination
    ) {

      /*
      |--------------------------------------------------------------------------
      | Disconnect Tone master from recording destination.
      |--------------------------------------------------------------------------
      */

      Tone.getDestination()
        .disconnect(
          this.recordingDestination
        );


      this.recordingDestination =
        null;

    }

  }

}